name: Bench

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install packages
      run: yarn install --frozen-lockfile

    - name: Run suites
      run: yarn start
